config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  
  get "/help", to: "static_pages#help"

  get "/about", to: "static_pages#about"

  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  resources :users

  resources :account_activations, only: %i(edit)

  resources :password_resets, only: %i(new create edit update)

  resources :microposts, only: %i(create destroy)

  resources :relationships, only: %i(create destroy) do
    member do
      get :following, to: "relationships#index"
      get :followers, to: "relationships#show"
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("static_pages.name"), "http://www.railstutorial.org/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about"), about_path %></li>
      <li><%= link_to t("static_pages.contact"), contact_path %></li>
      <li><%= link_to t("static_pages.news"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("static_pages.sample_app"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home"), root_path %></li>
        <li><%= link_to t("static_pages.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("layouts.header.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              data: {toggle: "dropdown"} do %>
              <%= t "header.account" %>
              <%= content_tag "b", "", class: "caret" %>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("layouts.header.profile"), current_user %></li>
              <li><%= link_to t("layouts.header.settings"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("static_pages.logout"), logout_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("static_pages.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application",
      media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>